### ISSUE TITLE
Could we add a link to the log to intercept?

### ISSUE THREAD

**Issue by DanielSiepmann** [TYPO3-Documentation/t3docs-ci-deploy#2]
I remember we had a link to the rendering log for each build when we used bamboo.
Would it be possible to have the same feature again?
That would make debugging for authors and team easier. The log was linked from the `Last rendered` column.

Maybe it's possible to add the version number and extension key (or other identifier) to the output at https://github.com/TYPO3-Documentation/t3docs-ci-deploy/actions/workflows/main-rendering.yml ? That would also help to identify the corresponding rendering log.

**Comment by susannemoog** [comment]
https://intercept.typo3.com/admin/docs/deployments here you go.
