### ISSUE TITLE
Scripts missing after home/root deployment

### ISSUE THREAD

**Issue by susannemoog** [TYPO3-Documentation/t3docs-ci-deploy#5]
The files piwik.js and extension-search.js currently need to be manually linked after every merge/deployment of the root repository. That should instead be done automatically by the deployment action.
`cd Web/Home`
`ln -sn res/js/piwik.js .`
`ln -sn res/js/extensions-search.js .`

**Comment by DavidBruchmann** [comment]
I think this can be closed, just the linked issue has to be resolved.  
@linawolf
